# -------------------------------------------------
# Type
# -------------------------------------------------
- name: bug
  color: faadaf
  description: "Something is broken"

- name: chore
  color: ffffff
  description: "A chore"

- name: discussion
  color: bebaf4
  description: "Discussing a topic with no specific actions yet"

- name: enhancement
  color: a2eeef
  description: "Improve something"

- name: feature
  color: b0f0fa
  description: "New feature or request"

- name: documentation
  color: f9d0c4
  description: "Improve or add to documentation"

- name: question
  color: d876e3
  description: "A question"

- name: duplicate
  color: cfd3d7
  description: "This issue or pull request already exists"

- name: invalid
  color: cfd3d7
  description: "This doesn't seem right"

- name: wontfix
  color: ffffff
  description: "This will not be worked on"

- name: help wanted
  color: 008672
  description: "Could use some help from maintainers and contributors."

# -------------------------------------------------
# Status
# prefixed with "needs"
# -------------------------------------------------
- name: needs attention
  color: 6d626c
  description: "It's been a while since this was pushed on. Needs attention from the owner or a maintainer."

- name: needs review
  color: 8c918c
  description: "Needs review from a contributor."

- name: needs info
  color: d0cfcc
  description: "Needs further information from the user"

# -------------------------------------------------
# Skill level
# prefixed with "good"
# -------------------------------------------------
- name: good first issue
  color: "159818"
  description: Clearly described and easy to accomplish. Good for beginners to the project.

- name: good second issue
  color: 5319e7
  description: Clearly described, educational, but less trivial than "good first issue".

# -------------------------------------------------
# Status
# prefixed with "status:"
# -------------------------------------------------
- name: status:in progress
  color: FEC6FB
  description: "In progress"

- name: status:on hold
  color: E58587
  description: "On hold"

# -------------------------------------------------
# Priority
# prefixed with "p" and colors span yellow to red
# -------------------------------------------------
- name: P3
  color: ffff33
  description: "Affects a small number of users or is largely cosmetic"

- name: P2
  color: ffc133
  description: "Affects more than a few users but doesn't prevent core functions"

- name: P1
  color: ff5233
  description: "Affects a large population and inhibits work"

# -------------------------------------------------
# MoSCoW
# -------------------------------------------------
- name: COULD
  color: 54AFFA
  description: "Could be useful"

- name: SHOULD
  color: 91A1B7
  description: "Nice to have"

- name: MUST
  color: EA0248
  description: "Must have"

# -------------------------------------------------
# Area
# -------------------------------------------------
- name: security
  color: D93F0B
  description: "Security related"

- name: legal
  color: 165E58
  description: "Legal"

- name: config
  color: 1586c0
  description: ""

- name: privacy
  color: 8DF9C3
  description: "Privacy related"

- name: performance
  color: "AE562E"
  description: ""

- name: build
  color: 03DB41
  description: "Related to the build"

- name: dependencies
  color: 04DB41
  description: "Related to the dependencies"

- name: a11y
  color: 1B8B38
  description: "Accessibility"

- name: i18n
  color: 2CB798
  description: "Internationalization"

- name: ui
  color: D5A4D6
  description: "User Interface (UI)"

- name: ux
  color: 830AC6
  description: "User Experience (UX)"

- name: dx
  color: 860AB3
  description: "Developer Experience (DX)"

- name: quality_assurance
  color: 89DEF3
  description: "Quality Assurance (QA)"

- name: maintenance
  color: 6AE049
  description: "Maintenance"

- name: code_quality
  color: b5ccfa
  description: "Improve code quality and reduce maintenance overhead"

- name: testing
  color: a0f9b4
  description: "Unit tests and/or continuous integration"

- name: deprecation
  color: f4e49a
  description: "Something is being removed"

- name: dev
  color: AE0AB9
  description: "Development related"

- name: tech
  color: 9A0E81
  description: "Technical task"

- name: support
  color: 32F3C0
  description: "Support task"

- name: troubleshooting
  color: 2EE6E3
  description: ""

- name: operations
  color: F18A86
  description: ""

- name: monitoring
  color: 6EC62D
  description: ""
